export const buffToImageArray = [
    ["Weakness", "public/Status/Weakness.webp"],
    ["Transcendent", "public/Status/Transcendent.webp"],
    ["Rampart", "public/Status/Rampart.webp"],
    ["Beserk", "public/Status/Beserk.webp"],
    ["Thrill of Battle", "public/Status/ThrillOfBattle.webp"],
    ["Stun", "public/Status/Stun.webp"],
    ["Reprisal", "public/Status/Reprisal.webp"],
    ["Astral Fire", "public/Status/AstralFire.webp"],
    ["Umbral Ice", "public/Status/UmbralIce.webp"],
    ["Lucid Dreaming", "public/Status/LucidDreaming.webp"],
    ["Addle", "public/Status/Addle.webp"],
    ["Aero", "public/Status/Aero.webp"],
    ["Bind", "public/Status/Bind.webp"],
    ["Mage's Ballad", "public/Status/MagesBallad.webp"],
    ["Raging Strikes", "public/Status/RagingStrikes.webp"],
    ["Sleep", "public/Status/Sleep.webp"],
    ["Straight Shot Ready", "public/Status/StraightShotReady.webp"],
    ["Thunder", "public/Status/Thunder.webp"],
    ["Thundercloud", "public/Status/Thundercloud.webp"],
    ["Venomous Bite", "public/Status/VenomousBite.webp"],
];
