export const Lv30Warrior = {
    role: "tank",
    image: "public\\PartyMembers\\Warrior_concept_art.jpg",
    maxHP: 35,
    maxMP: 5,
    STR: 4,
    DEX: 2,
    VIT: 5,
    INT: 0,
    MND: 1,
    physDef: 15,
    magDef: 12,
    VIG: 11,
    move: 5,
};

export const Lv40Warrior = {
    role: "tank",
    image: "public\\PartyMembers\\Warrior_concept_art.jpg",
    maxHP: 35,
    maxMP: 5,
    STR: 4,
    DEX: 2,
    VIT: 5,
    INT: 0,
    MND: 1,
    physDef: 15,
    magDef: 12,
    VIG: 11,
    move: 5,
};

export const Lv50Warrior = {
    role: "tank",
    image: "public\\PartyMembers\\Warrior_concept_art.jpg",
    maxHP: 35,
    maxMP: 5,
    STR: 4,
    DEX: 2,
    VIT: 5,
    INT: 0,
    MND: 1,
    physDef: 15,
    magDef: 12,
    VIG: 11,
    move: 5,
};
